import requests
import re
import urllib

to_game_name = {}
to_game_name['antimage']='Anti-Mage'
to_game_name['axe']='Axe'
to_game_name['bane']='Bane'
to_game_name['bloodseeker']='Bloodseeker'
to_game_name['crystal_maiden']='Crystal Maiden'
to_game_name['drow_ranger']='Drow Ranger'
to_game_name['earthshaker']='Earthshaker'
to_game_name['juggernaut']='Juggernaut'
to_game_name['mirana']='Mirana'
to_game_name['nevermore']='Shadow Fiend'
to_game_name['morphling']='Morphling'
to_game_name['phantom_lancer']='Phantom Lancer'
to_game_name['puck']='Puck'
to_game_name['pudge']='Pudge'
to_game_name['razor']='Razor'
to_game_name['sand_king']='Sand King'
to_game_name['storm_spirit']='Storm Spirit'
to_game_name['sven']='Sven'
to_game_name['tiny']='Tiny'
to_game_name['vengefulspirit']='Vengeful Spirit'
to_game_name['windrunner']='Windranger'
to_game_name['zuus']='Zeus'
to_game_name['kunkka']='Kunkka'
to_game_name['lina']='Lina'
to_game_name['lich']='Lich'
to_game_name['lion']='Lion'
to_game_name['shadow_shaman']='Shadow Shaman'
to_game_name['slardar']='Slardar'
to_game_name['tidehunter']='Tidehunter'
to_game_name['witch_doctor']='Witch Doctor'
to_game_name['riki']='Riki'
to_game_name['enigma']='Enigma'
to_game_name['tinker']='Tinker'
to_game_name['sniper']='Sniper'
to_game_name['necrolyte']='Necrophos'
to_game_name['warlock']='Warlock'
to_game_name['beastmaster']='Beastmaster'
to_game_name['queenofpain']='Queen of Pain'
to_game_name['venomancer']='Venomancer'
to_game_name['faceless_void']='Faceless Void'
to_game_name['skeleton_king']='Wraith King'
to_game_name['death_prophet']='Death Prophet'
to_game_name['phantom_assassin']='Phantom Assassin'
to_game_name['pugna']='Pugna'
to_game_name['templar_assassin']='Templar Assassin'
to_game_name['viper']='Viper'
to_game_name['luna']='Luna'
to_game_name['dragon_knight']='Dragon Knight'
to_game_name['dazzle']='Dazzle'
to_game_name['rattletrap']='Clockwerk'
to_game_name['leshrac']='Leshrac'
to_game_name['furion']='Nature\'s Prophet'
to_game_name['life_stealer']='Lifestealer'
to_game_name['dark_seer']='Dark Seer'
to_game_name['clinkz']='Clinkz'
to_game_name['omniknight']='Omniknight'
to_game_name['enchantress']='Enchantress'
to_game_name['huskar']='Huskar'
to_game_name['night_stalker']='Night Stalker'
to_game_name['broodmother']='Broodmother'
to_game_name['bounty_hunter']='Bounty Hunter'
to_game_name['weaver']='Weaver'
to_game_name['jakiro']='Jakiro'
to_game_name['batrider']='Batrider'
to_game_name['chen']='Chen'
to_game_name['spectre']='Spectre'
to_game_name['doom_bringer']='Doom'
to_game_name['ancient_apparition']='Ancient Apparition'
to_game_name['ursa']='Ursa'
to_game_name['spirit_breaker']='Spirit Breaker'
to_game_name['gyrocopter']='Gyrocopter'
to_game_name['alchemist']='Alchemist'
to_game_name['invoker']='Invoker'
to_game_name['silencer']='Silencer'
to_game_name['obsidian_destroyer']='Outworld Devourer'
to_game_name['lycan']='Lycan'
to_game_name['brewmaster']='Brewmaster'
to_game_name['shadow_demon']='Shadow Demon'
to_game_name['lone_druid']='Lone Druid'
to_game_name['chaos_knight']='Chaos Knight'
to_game_name['meepo']='Meepo'
to_game_name['treant']='Treant Protector'
to_game_name['ogre_magi']='Ogre Magi'
to_game_name['undying']='Undying'
to_game_name['rubick']='Rubick'
to_game_name['disruptor']='Disruptor'
to_game_name['nyx_assassin']='Nyx Assassin'
to_game_name['naga_siren']='Naga Siren'
to_game_name['keeper_of_the_light']='Keeper of the Light'
to_game_name['wisp']='Io'
to_game_name['visage']='Visage'
to_game_name['slark']='Slark'
to_game_name['medusa']='Medusa'
to_game_name['troll_warlord']='Troll Warlord'
to_game_name['centaur']='Centaur Warrunner'
to_game_name['magnataur']='Magnus'
to_game_name['shredder']='Timbersaw'
to_game_name['bristleback']='Bristleback'
to_game_name['tusk']='Tusk'
to_game_name['skywrath_mage']='Skywrath Mage'
to_game_name['abaddon']='Abaddon'
to_game_name['elder_titan']='Elder Titan'
to_game_name['legion_commander']='Legion Commander'
to_game_name['ember_spirit']='Ember Spirit'
to_game_name['earth_spirit']='Earth Spirit'
to_game_name['terrorblade']='Terrorblade'
to_game_name['phoenix']='Phoenix'
to_game_name['oracle']='Oracle'
to_game_name['techies']='Techies'
to_game_name['winter_wyvern']='Winter Wyvern'

query_url = 'http://www.dota2.com/heroes/'

response = requests.get(query_url)

pattern = r'http://cdn.dota2.com/apps/dota2/images/heroes/[a-z_]+_hphover.png'
image_urls = re.findall(pattern, response.content)

print len(image_urls)

for url in image_urls:
	hero_name = to_game_name[url[url.rfind('/')+1:-12]].lower().replace(' ', '')
	file_path = 'result/heroes/%s.png' % hero_name
	urllib.urlretrieve (url, file_path)
	print file_path